version: '3'
services:
  server:
    container_name: picServerV2
    build:
      context: ./server
    ports:
      - "4000:4000"
    networks:
      - pic-net
  web:
    container_name: picClientV2
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - pic-net
networks:
  pic-net:
    name: pic