version: '3'
services:
  web:
    container_name: picbed-client-v2
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge